add escape and unescape

diff --git a/bake2 b/bake2
--- a/bake2
+++ b/bake2
@@ -96,6 +96,14 @@ set -o pipefail  # default pipeline status==last command status, If set, status=
 # https://github.com/spf13/pflag
 # https://oclif.io/docs/flags
 
+# know bash version
+# ref: https://ftp.gnu.org/gnu/bash/
+# 1. ${parameter@operator} : from 2016 bash 4.4
+#      ${parameter@Q} quoted in a format that can be reused as input
+#      ${parameter@E} expanded as with the $'...' quoting mechansim
+#      ${parameter@A} an assignment statement or declare command
+# 2. associative array : from 2009 bash 4.0
+#    declare -A
 _on_error() {
   echo "trapped an error: ↑ , trace: ↓" >&2
   _stack_frame
@@ -105,15 +113,14 @@ _on_error() {
 trap "_on_error" ERR
 # todo trap exit and kill all subprocess
 
-
 # check bake dependencies
-if ((BASH_VERSINFO[0] < 4)); then
-  echo "Error: It's 2082 ，Your bash is still this version(BASH_VERSINFO: ${BASH_VERSINFO[*]})，Please install bash 4+:
-  apt install bash  # ubuntu
-  brew install bash # mac"
-  exit 1
+if (( BASH_VERSINFO[0] < 4 || \
+     (BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] < 4) ))  ; then
+    echo "Error: It's 2082 ，Your bash is still this version(BASH_VERSINFO: ${BASH_VERSINFO[*]})，Please install bash 4.4+:
+    apt install bash  # ubuntu
+    brew install bash # mac"
+    exit 1
 fi
-
 
 # copy from flutter
 # ----------------------
@@ -219,6 +226,30 @@ TYPE_CMD="type:cmd"
 # Usage: bake.str.cutLeft <str> <left>
 # bake.path.dirname a/b/c  a/b    => c
 bake.str.cutLeft(){ printf "${1#$2}"; }
+
+# escape to 'xxx' or $'xxx'
+bake.str.escape() {
+  #  from 2016 bash 4.4
+  #  ${parameter@Q} : quoted in a format that can be reused as input
+  # to 'xxx' or $'xxx'
+#  printf '%s' "${1@Q}" ;
+  for e  in "$@"; do
+    printf '%s\n' "${e@Q}" ;
+  done
+}
+
+# unescape from 'xxx' or $'xxx'
+bake.str.unescape() {
+  for e in "$@"; do
+    local result=${e}
+    [[ "$e" == "\$'"*"'" ]] && result="${e:2:-1}"
+    [[ "$e" == "'"*"'" ]] && result="${e:1:-1}"
+
+    #  from 2016 bash 4.4
+    #  ${parameter@E} expanded as with the $'...' quoting mechansim
+    printf '%s' "${result@E}" ;
+  done
+}
 
 # Usage: bake.str.split <str> [delimiter:default /]
 bake.str.split() {
@@ -394,74 +425,7 @@ function bake.opt.value(){
   local cmd="$1" opt="$2"
   printf '%s' "${_data["$cmd/opts/$opt/value"]}"
 }
-# Usage: bake.opt.parse <cmd:default _root> [arg1] [arg2] ...
-function bake.opt.parse_old() {
-    local cmd; cmd="${1:_root}"
-    shift
-    # key is -h --help ... candidate words ,
-    # value is optPath
-    declare -A allOptOnCmdChain;
 
-    # dynamic opt variable map : optPath:optVarName
-    # Why use dynamic variables: because the variable name is not fixed
-    # and We want to manipulate arrays(list type opt) more conveniently
-    declare -A matchedOptVars;
-
-    # collect opt from command chain : _root>pub>pub.get
-    #   root option first , priority low -> priority high:
-    for optPath in $(bake.opt.cmd_chain_opts "$cmd" | bake.str.revertLines ); do
-      local opt ; opt=$(bake.path.basename "$optPath")
-      local abbr ; abbr=${_data["$optPath/abbr"]}
-      allOptOnCmdChain["--$opt"]="${optPath}"
-      if [[ "$abbr" != "" ]] ; then allOptOnCmdChain["-$abbr"]="${optPath}" ; fi
-    done
-
-
-    # can use to: shift $optShift
-    local optShift; optShift=0
-
-
-    # while all args , until it is not opt
-    while (( $# > 0 )); do
-      # match $1 arg in allOptOnCmdChain, guess $1 is a "-h" "-help" ...
-      local optPath; optPath=${allOptOnCmdChain[$1]}
-      # if next arg not a opt , parsing complete;
-      if [[ "$optPath" == "" ]] ; then break;  fi
-
-      # matched, save it
-      local opt; opt=$(bake.path.basename "$optPath")
-
-      matchedOptVars["$optPath"]="__matched_opt_$opt"
-      # reference to the current dynamic  opt variable
-      declare -n matched_opt=${matchedOptVars[$optPath]};
-
-      # remove the prefix：build.@fields.opts.base_uri => base_uri
-      local optType; optType=${_data["$optPath/type"]}
-
-      case $optType in
-        bool)   _data[$optPath/value]=true;
-                matched_opt=true;
-                optShift=$((optShift+1)) ;  shift;;
-        string) [[ "$2" == "" ]] && echo "error: opt need a value: --$opt <value> " >&2 && return 1 ;
-                matched_opt="$2";
-                optShift=$((optShift+1)) ; shift 2 ;;
-        list)   [[ "$2" == "" ]] && echo "error: option $arg need a value arg: $arg <value> " >&2 && return 1 ;
-                # array add element
-                matched_opt+=("$2");
-                optShift=$((optShift+2)) ; shift 2 ;;
-        *) echo "parse error: not support $cmd.opts.$opt.type: <$optType> " >&2 ; return 1 ;;
-      esac
-    done
-
-    local resultStr;
-    for optPath in "${!matchedOptVars[@]}";do
-      local opt; opt=$(bake.path.basename "$optPath")
-      declare -n matched_opt="${matchedOptVars[$optPath]}";
-      resultStr+="$(printf 'declare %s=%q;\\n' "$opt" "$matched_opt"  )"
-    done
-    resultStr+="declare optShift=$optShift;\n"
-    echo -e "$resultStr" # -e show raw string
-}
 
 # Usage: bake.opt.parse <cmd:default _root> [arg1] [arg2] ...
 function bake.opt.parse() {
@@ -483,8 +447,7 @@ function bake.opt.parse() {
     # Why use dynamic variables: because the variable name is not fixed
     # and We want to manipulate arrays(list type opt) more conveniently
     local -A optVars;
-    local -i optShift; optShift=0
-
+    local totalArgs=$#
     # while all args , until it is not opt
     while (( $# > 0 )); do
       # match $1 arg in allOptOnCmdChain, guess $1 is a "-h" "-help" ...
@@ -492,36 +455,92 @@ function bake.opt.parse() {
       # if next arg not a opt , parsing complete;
       if [[ "${optPath}" == "" ]] ; then break;  fi
 
-      local opt; opt=$(bake.path.basename "$optPath")
-      local optType; optType=${_data["$optPath/type"]}
-
-      optVars["$optPath"]="_opt_value_$opt"
+      # _opt_value_ prefix : avoid conflicts in the current context
+      optVars["$optPath"]="_opt_value_$(bake.path.basename "$optPath")"
       declare "${optVars[$optPath]}"
       # reference to the current dynamic  opt variable
       declare -n currentOptValue=${optVars[$optPath]};
-#      echo "list opt: $optPath:[$optType] -  $1 = $2" >&2
 
+      local optType; optType=${_data["$optPath/type"]}
       case $optType in
         bool)   currentOptValue=true
-                shift ; (( optShift+=1 )) ;;
-        string) [[ ! "${2+declare}" ]] && echo "error: opt need a value: $arg <value> " >&2 && return 1 ;
+               shift 1  ;;
+        string) [[ ! "${2+declare}" ]] && echo "parse error: opt need a value: $arg <value> " >&2 && return 1 ;
                 currentOptValue="$2"
-                shift 2 ; (( optShift+=2 )) ;;
-        list)   [[ ! "${2+declare}" ]] && echo "error: opt need a value: $arg <value> " >&2 && return 1 ;
+               shift 2  ;;
+        list)   [[ ! "${2+declare}" ]] && echo "parse error: opt need a value: $arg <value> " >&2 && return 1 ;
                 currentOptValue+=("$2"); # array add
-                shift 2 ; (( optShift+=2 )) ;;
+               shift 2  ;;
         *) echo "parse error: not support $optPath.type: <$optType> " >&2 ; return 1 ;;
       esac
     done
 
     local resultStr;
     for optPath in "${!optVars[@]}";do
-      declare "${optVars[$optPath]}" # declare dynamic variable
       local declareStr; declareStr=$(declare -p "${optVars[$optPath]}")
-      resultStr+="${declareStr/#declare*_opt_value_/declare };\n"
+      resultStr+="${declareStr/#*_opt_value_/declare };\n"
     done
-    resultStr+="declare optShift=$optShift;\n"
-    echo -e "$resultStr" # -e show raw string
+    resultStr+="declare optShift=$(( totalArgs - $# ));\n"
+    echo -e "$resultStr" # echo -e : unescapes backslash
+}
+
+
+# Usage: bake.opt.parse <cmd:default _root> [arg1] [arg2] ...
+function bake.opt.parsenew() {
+    local cmd; cmd="${1:_root}"
+    shift # shift cmd arg, left all is options maybe
+    # key is -h --help ... candidate words ,
+    # value is optPath
+    declare -A allOptOnCmdChain;
+    # collect opt from command chain : _root>pub>pub.get
+    #   root option first , priority low -> priority high:
+    for optPath in $(bake.opt.cmd_chain_opts "$cmd" | bake.str.revertLines ); do
+      local opt ; opt=$(bake.path.basename "$optPath")
+      local abbr ; abbr=${_data["$optPath/abbr"]}
+      allOptOnCmdChain["--$opt"]="${optPath}"
+      if [[ "$abbr" != "" ]] ; then allOptOnCmdChain["-$abbr"]="${optPath}" ; fi
+    done
+
+    # dynamic opt variable map : optPath:optVarName
+    # Why use dynamic variables: because the variable name is not fixed
+    # and We want to manipulate arrays(list type opt) more conveniently
+    local -A optVars;
+    local totalArgs=$#
+    # while all args , until it is not opt
+    while (( $# > 0 )); do
+      # match $1 arg in allOptOnCmdChain, guess $1 is a "-h" "-help" ...
+      local optPath; optPath=${allOptOnCmdChain[$1]}
+      # if next arg not a opt , parsing complete;
+      if [[ "${optPath}" == "" ]] ; then break;  fi
+      local optName;optName=$(bake.path.basename "$optPath")
+      # _opt_value_ prefix : avoid conflicts in the current context
+      optVars["$optPath"]="_opt_value_$(bake.path.basename "$optPath")"
+      declare "${optVars[$optPath]}"
+      # reference to the current dynamic  opt variable
+      declare -n currentOptValue=${optVars[$optPath]};
+
+      local optType; optType=${_data["$optPath/type"]}
+      case $optType in
+        bool)  declare -p $optName=true
+               printf "\n" "$(declare -p $optName)"
+               shift 1  ;;
+        string) [[ ! "${2+declare}" ]] && echo "parse error: opt need a value: $arg <value> " >&2 && return 1 ;
+               declare -p $optName="$2"
+               printf "%s\n" "$(declare -p $optName)"
+               shift 2  ;;
+        list)   [[ ! "${2+declare}" ]] && echo "parse error: opt need a value: $arg <value> " >&2 && return 1 ;
+               printf "declare %s+=($'%q');\n" "$optName" "$2"
+               shift 2  ;;
+        *) echo "parse error: not support $optPath.type: <$optType> " >&2 ; return 1 ;;
+      esac
+    done
+
+#    local resultStr;
+#    for optPath in "${!optVars[@]}";do
+#      local declareStr; declareStr=$(declare -p "${optVars[$optPath]}")
+#      resultStr+="${declareStr/#*_opt_value_/declare };\n"
+#    done
+    printf 'declare optShift=%s;\n' "$(( totalArgs - $# ))"
 }
 bake.opt.set --cmd bake.cmd.set --name "cmd"         --type string --optHelp "cmd, function name"
 bake.opt.set --cmd bake.cmd.set --name "usage"       --type string --optHelp "usage"
@@ -529,6 +548,8 @@ bake.opt.set --cmd bake.cmd.set --name "summary"     --type string --optHelp "su
 bake.opt.set --cmd bake.cmd.set --name "description" --type string --optHelp "description, long help ,show on cmd help page"
 
 function bake.cmd.set(){
+  bake.opt.parse "${FUNCNAME[0]}" "$@"
+
   # 模版代码，放到每个需要使用option的函数中，然后就可以使用option了
   eval "$(bake.opt.parse "${FUNCNAME[0]}" "$@")"
   if [[ "$cmd" == "" ]]; then
