add bake.path.* func

diff --git a/bake2 b/bake2
--- a/bake2
+++ b/bake2
@@ -1,7 +1,11 @@
 #!/usr/bin/env bash
-set -o errtrace # trap inherited in sub script
-set -o errexit
-set -o functrace # If set, any trap on DEBUG and RETURN are inherited by shell functions
+set -o errtrace # -E trap inherited in sub script
+set -o errexit # -e
+set -o functrace # -T If set, any trap on DEBUG and RETURN are inherited by shell functions
+set -o pipefail  # default pipeline status==last command status, If set, status=any command fail
+#set -o nounset # -u: don't use it ,it is crazy, 1.bash version is diff Behavior 2.we need like this: ${arr[@]+"${arr[@]}"}
+# todo trap exit and kill all subprocess
+
 
 # bake == (bash)ake == 去make的bash工具
 # v0.2.20230515 目前仅在macos上跑过
@@ -174,7 +178,7 @@ function bake.cmd.register() {
         echo "error: function $functionName() can not contains '/' " >&2 && return 1
       fi
       local traverseUpPath
-      for traverseUpPath in $(bake.path_traverse_up "$functionName" ".");do
+      for traverseUpPath in $(bake.path.list_up "$functionName" ".");do
         local key; key=$([[ "$traverseUpPath" == / ]] && echo "/" || echo "$traverseUpPath" )
         _cmdTree["$traverseUpPath"]=""
       done
@@ -187,27 +191,10 @@ function bake.cmd.register() {
     done <<< "$(compgen -A function)"
 }
 
-# Usage: bake.path_traverse_up <str> <delimiter:"/">
-# sample:
-#   bake.path_traverse_up a.b "."    => "a.b", "a", ""
-function bake.path_traverse_up()(
-  local path=$1 delimiter=${2:-/}
 
-  current="${path}"
-  while [ "$current" != "" ]
-  do
-    printf '%s\n' "$current"
-    removed=${current%$delimiter*}
-    if [[ "$removed" == "$current" ]] ; then  break; fi
-    current="$removed"
-  done
-  # last is root
-  printf '\n'
-)
-
-# Usage: split <str> [delimiter:default \n]
+# Usage: bake.split <str> [delimiter:default /]
 bake.split() {
-  local str=$1 delimiter=${2:-.};
+  local str=$1 delimiter=${2:-/};
 #  # use <() process-substitution
 #  # don't use <<< "" its add newline
   local arr
@@ -215,13 +202,67 @@ bake.split() {
   printf '%s\n' "${arr[@]}"
 }
 
+# similar command dirname, but
+#     dirname root is ".", only work with "/"
+#     bake.path.dirname root is "" , can set delimiter
+# Usage: bake.path.dirname <str> [delimiter:default /]
+# bake.path.dirname a.b.c .    => a.b
+bake.path.dirname(){
+  local pathLikeStr="$1" delimiter="${2:-/}"
+  if [[ "$pathLikeStr" != *"$delimiter"* ]]; then printf '' ; return ; fi
+  printf '%s' "${pathLikeStr%$delimiter*}"
+}
+# similar command dirname, but
+#     dirname root is ".", only work with "/"
+#     bake.path.dirname root is "" , can set delimiter
+# Usage: bake.path.dirname <str> [delimiter:default /]
+# bake.path.dirname a.b.c .    => a.b
+bake.path.first(){
+  local pathLikeStr="$1" delimiter="${2:-/}"
+  # if /a/b/c
+  if [[ "$pathLikeStr" == "$delimiter"* ]] ; then
+    local x; x=$(bake.str.cutLeft "$pathLikeStr" "$delimiter")
+    printf "$delimiter$(bake.path.first "$x" "$delimiter" )"
+  else # a/b/c
+    printf "${pathLikeStr%%$delimiter*}"
+  fi
+}
+# similar command basename
+# Usage: bake.path.basename <str> [delimiter:default /]
+bake.path.basename(){
+  local pathLikeStr="$1" delimiter="${2:-/}"
+  # ${1##*/}  => ## left remove until last "/"
+  printf "${pathLikeStr##*$delimiter}";
+}
+# Usage: bake.path.list_up <str> <delimiter:"/">
+# sample:
+#   bake.path.list_up a.b "."    => "a.b", "a", ""
+function bake.path.list_up()(
+  local path=$1 delimiter=${2:-/}
+
+  current="${path}"
+
+  while
+    printf '%s\n' "$current"
+    local _dirname="$(bake.path.dirname "$current" "$delimiter")"
+    if [[ "$_dirname" == "$current" ]] ; then  break; fi
+    current="$_dirname"
+
+    [[ "$current" != "" ]]  # while condition
+  do true; done
+)
+# Usage: bake.str.cutLeft <str> <left>
+# bake.path.dirname a/b/c  a/b    => c
+bake.str.cutLeft(){ printf "${1#$2}"; }
+
 # Usage: bake.opt.match <cmd> <arg>
 # match a <arg> is a option return optionDataPath else return ""
 # Sample: bake.opt.match "build" "--dir" someDir
 #      => "build.opts.dir"
 function bake.opt.match()(
   local cmd=$1 arg=$2
-  for traverseUpCmd in $(bake.path_traverse_up "$cmd" "." ) ; do
+  local traverseUpCmd
+  for traverseUpCmd in $(bake.path.list_up "$cmd" "." ) ; do
     local opt;
     for opt in $(bake.data.children "$traverseUpCmd/opts"); do
        local abbr; abbr=${_data["$traverseUpCmd/opts/$opt/abbr"]}
@@ -341,7 +382,6 @@ function bake.main() {
     if [[ "$cmd" == "" ]] ; then bake.help "" ; return 0;  fi
     # parse opts
     eval "$(bake.opt.parse "$cmd" "$@")"
-    bake.opt.parse "$cmd" "$@"
 
     if ! declare -f "$cmd" >/dev/null 2>&1; then
       _error "Error: 404 ,cmd '${cmd}' not define, please define cmd function '${cmd}()'"
