感觉新结构简化很多，已完成cmd执行，还差help展示

diff --git a/bake2 b/bake2
--- a/bake2
+++ b/bake2
@@ -33,22 +33,12 @@ set -o functrace #trap inherited in function
 
 # copy from flutter
 # ----------------------
-# On Mac OS, readlink -f doesn't work, so follow_links traverses the path one
+# On Mac OS, readlink -f doesn't work, so bake.readlink traverses the path one
 # link at a time, and then cds into the link destination and find out where it
 # ends up.
-#
-# The returned filesystem path must be a format usable by Dart's URI parser,
-# since the Dart command line tool treats its argument as a file URI, not a
-# filename. For instance, multiple consecutive slashes should be reduced to a
-# single slash, since double-slashes indicate a URI "authority", and these are
-# supposed to be filenames. There is an edge case where this will return
-# multiple slashes: when the input resolves to the root directory. However, if
-# that were the case, we wouldn't be running this shell, so we don't do anything
-# about it.
-#
 # The function is enclosed in a subshell to avoid changing the working directory
 # of the caller.
-function bake.follow_links() (
+function bake.readlink() (
   cd -P "$(dirname -- "$1")"
   file="$PWD/$(basename -- "$1")"
   while [[ -L "$file" ]]; do
@@ -65,10 +55,12 @@ function bake.follow_links() (
 ##########################################
 
 declare BAKE_DIR
-BAKE_DIR=$(dirname "$(bake.follow_links "${BASH_SOURCE[0]}")")
-# 首先进入项目根目录，这样函数里就可以用相对路径，简化命令
-cd "${BAKE_DIR}"
+BAKE_PATH="$(bake.readlink "${BASH_SOURCE[0]}")"
+BAKE_DIR="$(dirname "$BAKE_PATH")"
+BAKE_FILE="$(basename "$BAKE_PATH")"
 
+# BAKE_DIR is workdir
+cd "${BAKE_DIR}"
 
 # Simulating object-oriented data structures with flat associative arrays
 # {
@@ -97,24 +89,54 @@ cd "${BAKE_DIR}"
 #   "otherVar": "other value"
 # }
 # The above data structures are flattened into the following variables:
-#  _data[cmds.pub.name]="pub"
-#  _data[cmds.pub.shortHelp]="flutter pub"
-#  _data[cmds.pub.options.mirror.name]="mirror"
-#  _data[cmds.pub.options.mirror.type]="string"
-#  _data[cmds.pub.options.mirror.abbr]="m"
-#  _data[cmds.pub.cmds.get.name]="get"
-#  _data[cmds.pub.cmds.get.shortHelp]="flutter pub get"
-#  _data[cmds.pub.cmds.get.options.verbose.name]="verbose"
-#  _data[cmds.pub.cmds.get.options.verbose.abbr]="v"
-#  _data[cmds.build.shortHelp]="flutter build"
+#  _data[bake.shortHelp]="bake root cmd"
+#  _data[bake.help]="bake root cmd"
+#  _data[bake.cmds.pub.name]="pub"
+#  _data[bake.cmds.pub.shortHelp]="flutter pub"
+#  _data[bake.cmds.pub.options.mirror.name]="mirror"
+#  _data[bake.cmds.pub.options.mirror.type]="string"
+#  _data[bake.cmds.pub.options.mirror.abbr]="m"
+#  _data[bake.cmds.pub.cmds.get.name]="get"
+#  _data[bake.cmds.pub.cmds.get.shortHelp]="flutter pub get"
+#  _data[bake.cmds.pub.cmds.get.options.verbose.name]="verbose"
+#  _data[bake.cmds.pub.cmds.get.options.verbose.abbr]="v"
+#  _data[bake.cmds.build.shortHelp]="flutter build"
 #  _data[otherVar]="other value"
+## 数据操纵行为设计：
+# 放弃
+#bake.cmd.shortHelp          "/pub/get" "[mono project] flutter pub get"
+#bake.cmd.help               "/pub/get" "[mono project] flutter pub get"
+## cmd, optionName, abbr, default, useage
+#bake.cmd.option.add         "/pub/get" verbose v "bool" false "verbose mode"
+
+# 放弃: option的字段相对比较固定，分开写很累赘，但如果有新增字段就会比较麻烦
+#bake.cmd.option.help        "/pub/get" verbose verbose
+#bake.cmd.option.type        "/pub/get" verbose bool
+#bake.cmd.option.abbr        "/pub/get" verbose v
+# 放弃
+#declare -A _cmd=(
+#  [name]="pub"
+#  [shortHelp]="[mono project]Commands for managing Flutter packages"
+#)
+#bake.addCmd _cmd
+# 放弃
+#bake.cmd.option "/pub/get?options.verbose.name"      verbose
+#bake.cmd.option "/pub/get?options.verbose.type"      "bool"
+#bake.cmd.option "/pub/get?options.verbose.abbr"      v
+#bake.cmd.option "/pub/get?options.verbose.default"   false
+#bake.cmd.option "/pub/get?options.verbose.shortHelp" "verbose mode"
+# 放弃
+#_data[rootCmd.cmds.pub.cmds.get.options.verbose.name]="verbose"
+#_data[rootCmd.cmds.pub.cmds.get.options.verbose.type]="bool"
+#_data[rootCmd.cmds.pub.cmds.get.options.verbose.abbr]="v"
+
 declare -A _data
-declare _currentCmd=rootCmd
+
 ##########################################
 # bake common function
 ##########################################
 bake.on_error() {
-  echo "traped an error: ↑ , trace: ↓" >&2
+  echo "trapped an error: ↑ , trace: ↓" >&2
   bake.print_stack
 }
 
@@ -138,22 +160,21 @@ bake.run() {
   return $?
 }
 
+bake.error(){
+  echo -e "ERROR -【$(bake.project.current) ▶︎${FUNCNAME[1]}】-︎ $*" >&2
+}
+bake.info(){
+  echo -e "INFO  -【$(bake.project.current) ▶︎${FUNCNAME[1]}】-︎ $*" >&2
+}
 
-bake.currentProject(){
+bake.project.current(){
   local project
   project=$(basename "$PWD")
   [[ "$PWD" == "$BAKE_DIR" ]] && project="root"
   echo "$project"
 }
 
-bake.error(){
-  echo -e "ERROR -【$(bake.currentProject) ▶︎${FUNCNAME[1]}】-︎ $*" >&2
-}
-bake.info(){
-  echo -e "INFO  -【$(bake.currentProject) ▶︎${FUNCNAME[1]}】-︎ $*" >&2
-}
-
-bake.print_commands() {
+bake.cmd.list() {
   # for each _data key that starts with "cmds.", print the command name
   for key in "${!_data[@]}"; do
     if [[ "$key" == cmds.* ]]; then
@@ -166,20 +187,68 @@ bake.print_commands() {
   done
   return
 }
+function bake.cmd.cmdPath2dataPath(){
+  local cmdPath=$1
+  local cmdDataPath
+  [[ "/" == "$cmdPath" ]] && cmdDataPath="bake" || cmdDataPath="bake$cmdPath"
+  # replace all "\"
+  echo "${cmdDataPath//\//".cmds."}"
 
-function bake.setRootCmd() {
-  local -n cmdArg=$1
-  local cmdName=${cmdArg[name]}
-  _data[rootCmd.name]=${cmdArg[name]}
-  _data[rootCmd.shortHelp]=${cmdArg[shortHelp]}
-  _data[rootCmd.help]=${cmdArg[help]}
 }
-function bake.addCmd() {
-  local -n cmdArg=$1
-  local cmdName=${cmdArg[name]}
-  for key in "${!cmdArg[@]}"; do
-    _data[$_currentCmd.cmds.$cmdName.$key]=${cmdArg[$key]}
-  done
+function bake.cmd.set() {
+  local cmdPath=$1
+  local field=$2
+  local value=$3
+
+  local cmdDataPath
+  cmdDataPath="$(bake.cmd.cmdPath2dataPath "$cmdPath")"
+
+  _data[$cmdDataPath.$field]=${value}
+}
+
+
+
+function bake.cmd.main() {
+    # ensure all cmd register
+    local fullNames
+    fullNames=$(declare -F | grep -E "^declare -f (\/.*)$" | sed -r 's/^declare -f (\/.*)$/\1/')
+    readarray -t fullNames <<<"$fullNames"
+    for cmdFullname in ${fullNames[*]}; do
+      local dataPath
+      dataPath="$(bake.cmd.cmdPath2dataPath "$cmdFullname")"
+      if [[ ${_data[$dataPath.shortHelp]} == "" ]]; then
+        _data[$dataPath.shortHelp]="-";
+      fi
+    done
+
+    local cmdPath=""
+    # parse args :
+    #   ./bake pub get -v -b
+    #     -> { cmdPath:"/pub/get", args:"-v -b" }
+    #   ./bake -h
+    #     -> { cmdPath:"/", args:"-h" }
+    for arg in "$@"; do
+      local nextCmdPath
+      nextCmdPath="$cmdPath/$arg"
+      local toFind
+      toFind="$(bake.cmd.cmdPath2dataPath "$nextCmdPath")"
+      echo tofind:$toFind
+      if ( printf '%s\n' "${!_data[@]}" | grep "$toFind" ) > /dev/null ; then
+        cmdPath="$nextCmdPath" ;
+        shift ;
+      else
+        break;
+      fi
+    done
+    # if nothing cmd find then root cmd
+    [[ "$cmdPath" == "" ]] && cmdPath="/" || true
+    bake.info "cmd:$cmdPath args: ${*}"
+
+    if ! declare -f "$cmdPath" >/dev/null 2>&1; then
+      bake.error "Error: 404 ,cmd '${cmdPath}' not exists, please define cmd function '${cmdPath}()'"
+      exit 1
+    fi
+    $cmdPath "$@"
 }
 
 
@@ -189,101 +258,41 @@ function bake.addCmd() {
 
 # cmd settings use bash associative array
 # shellcheck disable=SC2034
-declare -A _cmd=(
-  [name]="bake"
-  [shortHelp]="root Command for flutter-note project"
-  [help]=$(cat <<- EOF
+bake.cmd.set "/" shortHelp            "[mono project] flutter pub get"
+bake.cmd.set "/" help                 "$(cat <<- EOF
 ____ _    _  _ ___ ___ ____ ____    _  _ ____ ___ ____
 |___ |    |  |  |   |  |___ |__/ __ |\ | |  |  |  |___
 |    |___ |__|  |   |  |___ |  \    | \| |__|  |  |___
 Usage:
-./bake [command] [options]
+./${BAKE_FILE} [command] [options]
 
-  ./bake       # 列子命令看帮助，
-  ./bake build # 子命令
-  ./bake run   # 子命令
+  ./${BAKE_FILE}       # 列子命令看帮助，
+  ./${BAKE_FILE} build # 子命令
+  ./${BAKE_FILE} run   # 子命令
 EOF
-  )
-)
-bake.setRootCmd _cmd
+)"
 
 ################################################
 ## pub
 ################################################
-declare -A _cmd=(
-  [name]="pub"
-  [shortHelp]="[mono project]Commands for managing Flutter packages"
-)
-bake.addCmd _cmd
-/pub(){
-    bake.run echo "run flutter pub [$*]"
-}
-
-
-declare -A _cmd=(
-  [shortHelp]="[mono project] flutter pub get"
-)
-bake.addCmd _cmd
-/pub/get(){
-  bake.run echo "flutter pub get"
-}
 
 # https://pub.dev/documentation/args/latest/args/ArgParser-class.html
 # https://github.com/spf13/pflag/blob/master/string_array.go
 #目前倾向的格式：
-bake.cmd.shortHelp          "/pub/get" "[mono project] flutter pub get"
-bake.cmd.help               "/pub/get" "[mono project] flutter pub get"
-# cmd, optionName, abbr, default, useage
-bake.cmd.option.add         "/pub/get" verbose v "bool" false "verbose mode"
-# 放弃: option的字段相对比较固定，分开写很累赘，但如果有新增字段就会比较麻烦
-#bake.cmd.option.help        "/pub/get" verbose verbose
-#bake.cmd.option.type        "/pub/get" verbose bool
-#bake.cmd.option.abbr        "/pub/get" verbose v
-# 放弃
-#declare -A _cmd=(
-#  [name]="pub"
-#  [shortHelp]="[mono project]Commands for managing Flutter packages"
-#)
-#bake.addCmd _cmd
-# 放弃
-#bake.cmd.option "/pub/get?options.verbose.name"      verbose
-#bake.cmd.option "/pub/get?options.verbose.type"      "bool"
-#bake.cmd.option "/pub/get?options.verbose.abbr"      v
-#bake.cmd.option "/pub/get?options.verbose.default"   false
-#bake.cmd.option "/pub/get?options.verbose.shortHelp" "verbose mode"
-# 放弃
-#_data[rootCmd.cmds.pub.cmds.get.options.verbose.name]="verbose"
-#_data[rootCmd.cmds.pub.cmds.get.options.verbose.type]="bool"
-#_data[rootCmd.cmds.pub.cmds.get.options.verbose.abbr]="v"
-/pub/get(){
-  bake.run echo "flutter pub get"
-}
 
-/pub/get?(){
-  /pub/get?shortHelp(){  echo "[mono project] flutter pub get" ; }
-  /pub/get?options(){
-    bake.cmd.option "/pub/get?options.verbose.name"      verbose
-    bake.cmd.option "/pub/get?options.verbose.type"      "bool"
-    bake.cmd.option "/pub/get?options.verbose.abbr"      v
-    bake.cmd.option "/pub/get?options.verbose.default"   false
-    bake.cmd.option "/pub/get?options.verbose.shortHelp" "verbose mode"
-  }
-  /pub/get(){
-    bake.run echo "[mono project] flutter pub get" ;
-  }
+bake.cmd.set "/pub/get" shortHelp            "[mono project] flutter pub get"
+bake.cmd.set "/pub/get" help                 "[mono project] flutter pub get"
+bake.cmd.set "/pub/get" options.verbose.name verbose
+bake.cmd.set "/pub/get" options.verbose.abbr v
+bake.cmd.set "/pub/get" options.verbose.type bool
+/pub/get(){
+    bake.run echo "run flutter pub [$*]"
 }
-bake.define.hortHelp "/pub/get" "[mono project] flutter pub get"
-bake.define.help     "/pub/get" "[mono project] flutter pub get"
 
 ################################################
 ## doctor
 ################################################
-declare -A _cmd=(
-  [name]="doctor"
-  [shortHelp]="doctor this project"
-)
-bake.addCmd _cmd
-function doctor(){
+function /doctor(){
   bake.info "doctor start -----------------------------------"
   for key in "${!_data[@]}"; do
     bake.info "$key=${_data[$key]:0:50}"
@@ -291,39 +300,9 @@ function doctor(){
   bake.info "doctor end -__----------------------------------"
 }
 
-_help() {
-  cat <<-'__EOF'
-____ _    _  _ ___ ___ ____ ____    _  _ ____ ___ ____
-|___ |    |  |  |   |  |___ |__/ __ |\ | |  |  |  |___
-|    |___ |__|  |   |  |___ |  \    | \| |__|  |  |___
-Usage:
-./bake [command] [options]
-
-Available Commands:
-__EOF
-
-  bake.print_commands
-}
-
-
 ##########################################
 # bake common entry script
 ##########################################
 trap " set +x; bake.on_error " ERR
 
-# if no args, show help
-if [ "$#" == 0 ]; then
-  _help # 根命令的帮助
-  echo
-  bake.error "missing command, please use './bake [command]'"
-  exit 1
-fi
-
-cmd="$1"
-shift
-if ! declare -f "$cmd" >/dev/null 2>&1; then
-  bake.error "Error: 404 ,command '${cmd}' not exists, please define command function '${cmd}()'"
-  exit 1
-fi
-
-/$cmd "$@"
+bake.cmd.main "$@"
